export interface SoftwareRecommendation {
  rank: number;
  name: string;
  tagline: string;
  price: string;
  bestFor: string;
  reasoning: string;
  pros: string[];
  cons: string[];
  affiliateUrl: string;
}

export interface AudiencePage {
  slug: string;
  title: string;
  heroHeadline: string;
  heroSubtext: string;
  audienceDescription: string;
  topRecommendations: SoftwareRecommendation[];
  keyFeatures: { icon: string; title: string; description: string }[];
  pricingTable: { software: string; starter: string; mid: string; enterprise: string; freeTrial: boolean }[];
  faqs: { question: string; answer: string }[];
  metaTitle: string;
  metaDescription: string;
}

export const audiences: Record<string, AudiencePage> = {
  "solo-attorneys": {
    slug: "solo-attorneys",
    title: "Best Legal Software for Solo Attorneys",
    heroHeadline: "Best Legal Software for Solo Attorneys in 2026",
    heroSubtext: "Affordable, intuitive practice management tools built for attorneys running their own practice -- without enterprise complexity or enterprise pricing.",
    audienceDescription: "Solo attorneys juggle every role: lawyer, accountant, marketer, and office manager. You need software that handles time tracking, billing, client communication, and document management without requiring an IT department. Affordability and ease of use matter more than deep integrations or team collaboration features. The right tool should pay for itself by capturing more billable hours and reducing administrative overhead.",
    topRecommendations: [
      {
        rank: 1,
        name: "MyCase",
        tagline: "Lowest entry price with full-featured practice management",
        price: "From $39/user/month",
        bestFor: "Solo attorneys switching from spreadsheets or pen-and-paper",
        reasoning: "MyCase Basic at $39/user/month is the most complete entry-level plan in legal software. You get full case management, time tracking, billing with online payments, a client portal, unlimited document storage, and legal calendaring. The 10-day free trial with no credit card required makes it risk-free to evaluate.",
        pros: ["Lowest starting price at $39/user/month", "10-day free trial, no credit card required", "Client portal included on all plans", "Unlimited document storage", "Built-in AI assistant (8am IQ) on Pro plan"],
        cons: ["Fewer integrations than Clio (~50 vs 250+)", "Limited API access on Basic plan"],
        affiliateUrl: "https://www.mycase.com/free-trial/",
      },
      {
        rank: 2,
        name: "PracticePanther",
        tagline: "Self-contained platform with native eSignature and texting",
        price: "From $49/user/month",
        bestFor: "Solo attorneys wanting fewer third-party subscriptions",
        reasoning: "PracticePanther Solo at $49/user/month includes document templates and task workflows that MyCase Basic does not. The Business plan adds native eSignature (unlimited) and built-in two-way texting, eliminating the need for DocuSign and separate messaging tools. Free data migration makes switching painless.",
        pros: ["Native eSignature eliminates DocuSign subscription", "Built-in two-way texting with clients", "Document templates and task workflows", "Free data migration from other platforms", "LEDES billing for insurance defense work"],
        cons: ["$10/month more than MyCase Basic entry price", "No built-in accounting"],
        affiliateUrl: "https://www.practicepanther.com/free-trial/",
      },
      {
        rank: 3,
        name: "Clio",
        tagline: "Best ecosystem for solos planning to grow",
        price: "From $49/user/month",
        bestFor: "Solo attorneys who plan to hire and scale their practice",
        reasoning: "Clio EasyStart is the right choice for solo attorneys who anticipate growth. Starting on Clio means 250+ integrations are available as you add tools, and upgrading within Clio is seamless. The industry-leading mobile app lets you manage your practice from court or on the road.",
        pros: ["250+ integrations for future growth", "Best mobile apps in the category", "Built-in e-signatures on EasyStart", "Industry-leading customer support", "Seamless upgrade path as practice grows"],
        cons: ["More expensive at scale than alternatives", "No built-in accounting"],
        affiliateUrl: "https://www.clio.com/signup/",
      },
    ],
    keyFeatures: [
      { icon: "\u23F1\uFE0F", title: "Automatic Time Tracking", description: "Capture every billable minute without manual timers. Solo attorneys lose 15-25% of billable hours without proper tracking tools." },
      { icon: "\U0001F4B3", title: "Online Payment Collection", description: "Let clients pay invoices online via credit card or ACH. Firms with online payments collect 30-40% faster than those relying on checks." },
      { icon: "\U0001F4F1", title: "Mobile Access", description: "Manage cases, track time, and communicate with clients from your phone. Essential for solos who work from court, home, and coffee shops." },
      { icon: "\U0001F4C4", title: "Document Templates", description: "Generate common legal documents from templates pre-filled with client data. Save 30-60 minutes per document versus manual creation." },
      { icon: "\U0001F465", title: "Client Portal", description: "Give clients 24/7 access to case updates, documents, and invoices. Reduces 'where is my case?' phone calls by up to 40%." },
      { icon: "\U0001F4CA", title: "Trust Accounting", description: "Built-in IOLTA trust accounting ensures bar compliance. Every platform reviewed includes trust accounting at no extra cost." },
    ],
    pricingTable: [
      { software: "MyCase", starter: "$39/user/mo", mid: "$89/user/mo", enterprise: "$109/user/mo", freeTrial: true },
      { software: "PracticePanther", starter: "$49/user/mo", mid: "$69/user/mo", enterprise: "$89/user/mo", freeTrial: true },
      { software: "Clio", starter: "$49/user/mo", mid: "$89/user/mo", enterprise: "$119/user/mo", freeTrial: true },
    ],
    faqs: [
      { question: "What is the cheapest legal software for solo attorneys?", answer: "MyCase Basic at $39/user/month (billed annually) is the lowest-priced full-featured legal practice management platform. It includes case management, time tracking, billing, a client portal, and unlimited document storage." },
      { question: "Do solo attorneys really need practice management software?", answer: "Yes. Solo attorneys using dedicated software capture 15-25% more billable hours than those using spreadsheets, according to industry research. The productivity gain typically pays for the software within the first week of use." },
      { question: "What features should a solo attorney prioritize?", answer: "Essential features: time tracking, billing and invoicing, trust accounting, client portal, document storage, and calendar management. Nice-to-have: eSignature, two-way texting, and intake forms." },
      { question: "Can I switch legal software later without losing data?", answer: "Yes. All major platforms offer data migration assistance. PracticePanther includes free data migration on their Business plan. Clio and MyCase also provide migration tools and support." },
      { question: "Is cloud-based legal software secure enough for client data?", answer: "Yes. Clio, MyCase, and PracticePanther all use AES-256 encryption, SOC 2 compliance, and role-based access controls. Cloud storage is generally more secure than local hard drives for solo attorneys." },
    ],
    metaTitle: "Best Legal Software for Solo Attorneys (2026) | CounselStack",
    metaDescription: "Compare the best legal practice management software for solo attorneys in 2026. MyCase, PracticePanther, and Clio ranked by price, features, and ease of use.",
  },

  "small-firms": {
    slug: "small-firms",
    title: "Best Legal Software for Small Law Firms",
    heroHeadline: "Best Legal Software for Small Law Firms in 2026",
    heroSubtext: "Practice management platforms that scale from 2 to 25 attorneys without the complexity or cost of enterprise solutions.",
    audienceDescription: "Small law firms (2-25 attorneys) face a unique challenge: they need collaboration features, shared calendaring, and team billing workflows, but they can't justify enterprise pricing or dedicate staff to software administration. The right platform should be easy to onboard new attorneys, provide firm-wide reporting, and handle multi-attorney matter assignment without requiring an IT department.",
    topRecommendations: [
      {
        rank: 1,
        name: "Clio",
        tagline: "Best overall platform for growing small firms",
        price: "From $89/user/month (Essentials)",
        bestFor: "Small firms building a professional legal tech stack",
        reasoning: "Clio Essentials at $89/user/month delivers the integration ecosystem no competitor matches. 250+ app connections mean your billing, document management, accounting, and communication tools all connect seamlessly. The client portal and document templates save hours weekly across the firm.",
        pros: ["250+ integrations for any workflow need", "Document and matter templates for consistency", "Client portal included on Essentials", "Best mobile apps for attorneys in court", "Full workflow automation on Advanced plan"],
        cons: ["More expensive than alternatives at entry level", "No built-in firm accounting"],
        affiliateUrl: "https://www.clio.com/signup/",
      },
      {
        rank: 2,
        name: "MyCase",
        tagline: "Best value with built-in AI for small firms",
        price: "From $89/user/month (Pro)",
        bestFor: "Small firms prioritizing usability and AI-assisted workflows",
        reasoning: "MyCase Pro matches Clio Essentials on price but beats it on simplicity and AI. The 8am IQ AI assistant helps with drafting and document review, unlimited two-way texting is included, and the interface is the cleanest in the category. For small firms prioritizing usability over integration depth, MyCase Pro is the better choice.",
        pros: ["Built-in AI assistant (8am IQ) for drafting", "Unlimited two-way texting included", "Cleanest interface in the category", "eSignature included on Pro plan", "10-day free trial, no credit card"],
        cons: ["Fewer integrations than Clio (~50 vs 250+)", "Limited API on lower plans"],
        affiliateUrl: "https://www.mycase.com/free-trial/",
      },
      {
        rank: 3,
        name: "PracticePanther",
        tagline: "Most self-contained platform at the $89 price point",
        price: "From $89/user/month (Business)",
        bestFor: "Firms wanting to minimize third-party tool subscriptions",
        reasoning: "PracticePanther Business includes native eSignature (unlimited), built-in two-way texting, LEDES billing, and free data migration. For small firms that want to minimize third-party tool subscriptions, PracticePanther is the most self-sufficient platform at the $89/user/month price point.",
        pros: ["Native eSignature (unlimited, no DocuSign needed)", "Built-in two-way texting at no extra cost", "LEDES billing for insurance defense", "Free data migration from other platforms", "VIP support on Business plan"],
        cons: ["Mid-tier pricing for entry-level plan", "Fewer integrations than Clio"],
        affiliateUrl: "https://www.practicepanther.com/free-trial/",
      },
    ],
    keyFeatures: [
      { icon: "\U0001F46B", title: "Multi-Attorney Collaboration", description: "Assign matters to multiple attorneys, share notes, and track team-wide deadlines from a single dashboard." },
      { icon: "\U0001F4CA", title: "Firm-Wide Reporting", description: "Track revenue, utilization rates, and matter profitability across all attorneys. Identify top performers and bottlenecks." },
      { icon: "\U0001F4C5", title: "Shared Calendaring", description: "Firm-wide calendar with court dates, deadlines, and statute of limitations tracking. Avoid conflicts and missed dates." },
      { icon: "\U0001F517", title: "Integration Ecosystem", description: "Connect with your existing tools -- accounting (QuickBooks), storage (Dropbox, Google Drive), communication (Slack, Teams)." },
      { icon: "\U0001F464", title: "Client Portal", description: "White-labeled portal for secure document sharing, invoice payments, and case status updates. Reduces support calls." },
      { icon: "\u2699\uFE0F", title: "Workflow Automation", description: "Automate repetitive tasks: intake follow-ups, document generation, billing reminders. Free up attorney time for billable work." },
    ],
    pricingTable: [
      { software: "Clio", starter: "$49/user/mo", mid: "$89/user/mo", enterprise: "$149/user/mo", freeTrial: true },
      { software: "MyCase", starter: "$39/user/mo", mid: "$89/user/mo", enterprise: "$109/user/mo", freeTrial: true },
      { software: "PracticePanther", starter: "$49/user/mo", mid: "$69/user/mo", enterprise: "$89/user/mo", freeTrial: true },
      { software: "CosmoLex", starter: "$109/user/mo", mid: "$129/user/mo", enterprise: "Custom", freeTrial: true },
    ],
    faqs: [
      { question: "What is the best legal software for a firm with 2-10 attorneys?", answer: "Clio Essentials ($89/user/month) is the best overall choice for firms with 2-10 attorneys due to its 250+ integrations and scalability. MyCase Pro ($89/user/month) is best for firms prioritizing simplicity and AI features." },
      { question: "How much should a small law firm budget for practice management software?", answer: "Budget $89-$119/user/month for quality practice management. For a 5-attorney firm on Clio Essentials, that's $445/month or $5,340/year. Annual billing saves 10-20% on all platforms." },
      { question: "Do small firms need separate accounting software?", answer: "Most do -- Clio, MyCase, and PracticePanther require QuickBooks or Xero for firm accounting. CosmoLex ($109/user/month) is the exception, including full double-entry accounting and eliminating the need for QuickBooks." },
      { question: "Can we migrate from our current software without downtime?", answer: "Yes. All major platforms offer migration support. PracticePanther includes free data migration. Clio and MyCase provide migration tools and dedicated support. Typical migration takes 1-2 weeks with parallel running." },
      { question: "What is the best legal software for a firm that handles multiple practice areas?", answer: "Clio is the strongest choice for multi-practice firms due to its custom matter types, 250+ integrations, and flexible workflow templates. You can configure different workflows for litigation, transactional, and family law matters." },
    ],
    metaTitle: "Best Legal Software for Small Law Firms (2026) | CounselStack",
    metaDescription: "Best legal practice management software for small law firms (2-25 attorneys) in 2026. Compare Clio, MyCase, and PracticePanther for pricing, features, and scalability.",
  },

  "mid-size-firms": {
    slug: "mid-size-firms",
    title: "Best Legal Software for Mid-Size Firms",
    heroHeadline: "Best Legal Software for Mid-Size Firms in 2026",
    heroSubtext: "Enterprise-grade capabilities for firms with 25-100+ attorneys -- without the complexity of legacy systems.",
    audienceDescription: "Mid-size firms (25-100+ attorneys) need software that handles complex billing structures, multi-office coordination, department-level reporting, and enterprise security requirements. Integration with existing systems (document management, accounting, HR) is critical. These firms often have dedicated IT staff and need platforms with robust APIs, SSO, and compliance features.",
    topRecommendations: [
      {
        rank: 1,
        name: "Clio",
        tagline: "Industry-leading ecosystem with 250+ integrations",
        price: "From $119/user/month (Advanced)",
        bestFor: "Mid-size firms needing deep integrations and workflow automation",
        reasoning: "Clio Advanced at $119/user/month is the strongest platform for mid-size firms. Automated workflows, custom reports, priority support, and the industry's largest integration ecosystem (250+ apps) make it the foundation for a modern legal tech stack. The Expand plan ($149/user/month) adds Clio Grow CRM for business development tracking.",
        pros: ["250+ integrations with enterprise tools", "Automated workflows and custom reports", "Priority support and live onboarding", "Clio Grow CRM on Expand plan", "SOC 2 compliance and robust API"],
        cons: ["Higher per-user cost at scale", "No built-in firm accounting"],
        affiliateUrl: "https://www.clio.com/signup/",
      },
      {
        rank: 2,
        name: "Smokeball",
        tagline: "Deepest document automation and automatic time tracking",
        price: "From $149/month (annual contract)",
        bestFor: "Mid-size firms with document-intensive practices",
        reasoning: "Smokeball stands out for mid-size firms processing high volumes of documents. Autotime automatically tracks every second spent on a case without manual timers -- critical for capturing billable hours across 25+ attorneys. The 20,000+ document template library and deep Microsoft 365 integration make it the best choice for document-heavy firms.",
        pros: ["Autotime captures every billable minute automatically", "20,000+ pre-built legal document templates", "Deep Microsoft 365 integration", "Practice area-specific workflows", "Automatic version control on all documents"],
        cons: ["Annual contract required", "Opaque per-user pricing", "Steeper learning curve for new users"],
        affiliateUrl: "https://www.smokeball.com/free-trial/",
      },
      {
        rank: 3,
        name: "CosmoLex",
        tagline: "Only platform with built-in full accounting",
        price: "From $109/user/month",
        bestFor: "Mid-size firms wanting to eliminate QuickBooks",
        reasoning: "CosmoLex is the only legal practice management platform with full double-entry accounting built in. For mid-size firms paying for QuickBooks plus a PM tool, CosmoLex consolidates everything into one platform. Trust accounting with 3-way reconciliation, P&L statements, and balance sheets are all included -- no sync issues, no data discrepancies.",
        pros: ["Full accounting eliminates QuickBooks subscription", "Trust accounting with 3-way reconciliation", "Single platform for PM + accounting", "No data sync issues between systems", "Comprehensive compliance reporting"],
        cons: ["Higher entry price than competitors", "Smaller integration library (~20)", "Less polished interface than Clio"],
        affiliateUrl: "https://www.cosmolex.com/free-trial/",
      },
    ],
    keyFeatures: [
      { icon: "\U0001F3E2", title: "Multi-Office Support", description: "Manage attorneys, matters, and billing across multiple office locations from a unified platform with location-based reporting." },
      { icon: "\U0001F4CA", title: "Department-Level Reporting", description: "Track revenue, utilization, and profitability by department, practice area, or partner. Board-ready reports on demand." },
      { icon: "\U0001F512", title: "Enterprise Security", description: "SOC 2 compliance, SSO integration, role-based access controls, and audit trails. Meet client security requirements for corporate work." },
      { icon: "\U0001F504", title: "Workflow Automation", description: "Automate matter opening, task assignment, billing processes, and client communications. Reduce administrative overhead across the firm." },
      { icon: "\U0001F517", title: "API & Integrations", description: "REST APIs and 250+ pre-built integrations connect with existing systems -- DMS, accounting, HR, and business intelligence tools." },
      { icon: "\U0001F4B0", title: "Complex Billing", description: "Handle split billing, matter-level budgets, LEDES/UTBMS compliance, and multi-currency billing for sophisticated client requirements." },
    ],
    pricingTable: [
      { software: "Clio", starter: "$89/user/mo", mid: "$119/user/mo", enterprise: "$149/user/mo", freeTrial: true },
      { software: "Smokeball", starter: "From $149/mo", mid: "Custom", enterprise: "Custom", freeTrial: true },
      { software: "CosmoLex", starter: "$109/user/mo", mid: "$129/user/mo", enterprise: "Custom", freeTrial: true },
    ],
    faqs: [
      { question: "What is the best legal software for firms with 25+ attorneys?", answer: "Clio Advanced ($119/user/month) is the best overall choice for mid-size firms due to its 250+ integrations, automated workflows, custom reports, and enterprise-grade security. Smokeball is best for document-intensive practices, and CosmoLex is best for firms wanting built-in accounting." },
      { question: "How do mid-size firms handle data migration?", answer: "All major platforms provide dedicated migration support for mid-size firms. Expect a 2-4 week migration timeline with parallel running. Request a dedicated migration specialist and negotiate migration costs as part of your contract." },
      { question: "Do mid-size firms need a dedicated DMS alongside practice management?", answer: "It depends on complexity. Clio and Smokeball have strong built-in document management. Firms with strict compliance requirements (M&A, banking) may benefit from a dedicated DMS like NetDocuments alongside their PM platform." },
      { question: "Can legal PM software integrate with our existing accounting system?", answer: "Clio integrates with QuickBooks and Xero. CosmoLex eliminates the need for separate accounting entirely. Smokeball also connects with QuickBooks. For mid-size firms, CosmoLex's built-in accounting eliminates the sync issues that plague QuickBooks integrations at scale." },
      { question: "What security certifications should we look for?", answer: "Look for SOC 2 Type II compliance, AES-256 encryption, and SSO support. Clio, MyCase, and CosmoLex all meet these requirements. Additionally, verify that the platform supports role-based access controls and maintains audit trails for compliance reporting." },
    ],
    metaTitle: "Best Legal Software for Mid-Size Firms (2026) | CounselStack",
    metaDescription: "Best legal practice management software for mid-size law firms (25-100+ attorneys) in 2026. Compare Clio, Smokeball, and CosmoLex for enterprise features, integrations, and pricing.",
  },

  "family-law": {
    slug: "family-law",
    title: "Best Legal Software for Family Law",
    heroHeadline: "Best Legal Software for Family Law in 2026",
    heroSubtext: "Practice management tools designed for the unique demands of divorce, custody, child support, and domestic relations cases.",
    audienceDescription: "Family law practices handle emotionally charged cases with complex document requirements, frequent court appearances, and high client communication volume. Attorneys need software that manages child support calculations, parenting plan templates, financial disclosure documents, and frequent status updates to anxious clients. The right platform reduces the administrative burden of custody schedules, asset division worksheets, and court filing deadlines.",
    topRecommendations: [
      {
        rank: 1,
        name: "Smokeball",
        tagline: "Best document automation for family law forms and filings",
        price: "From $149/month (annual contract)",
        bestFor: "Family law firms with heavy document volume",
        reasoning: "Smokeball's 20,000+ legal document template library includes extensive family law forms -- divorce petitions, custody agreements, parenting plans, financial affidavits, and property settlement agreements. Documents auto-fill from matter data, saving hours per case. The Autotime feature automatically tracks time without manual entry, critical for family law attorneys billing hourly.",
        pros: ["Extensive family law document templates", "Autotime captures every billable minute", "Deep Microsoft 365 integration for Word drafting", "Practice area-specific workflows for family law", "Automatic version control on all documents"],
        cons: ["Annual contract required", "Opaque pricing structure", "Steeper learning curve"],
        affiliateUrl: "https://www.smokeball.com/free-trial/",
      },
      {
        rank: 2,
        name: "MyCase",
        tagline: "Best client communication for high-touch family law practices",
        price: "From $39/user/month",
        bestFor: "Family law attorneys managing anxious clients",
        reasoning: "Family law clients are emotionally invested and demand frequent updates. MyCase addresses this with a client portal on all plans (even $39/month), unlimited two-way texting on Pro, and the 8am IQ AI assistant for drafting correspondence. The clean interface means less time learning software and more time with clients.",
        pros: ["Client portal on all plans reduces status calls", "Unlimited two-way texting on Pro plan", "AI assistant helps draft client correspondence", "Lowest entry price at $39/user/month", "10-day free trial, no credit card"],
        cons: ["Fewer integrations than Clio", "No family law-specific document templates"],
        affiliateUrl: "https://www.mycase.com/free-trial/",
      },
      {
        rank: 3,
        name: "Clio",
        tagline: "Best overall platform with custom family law workflows",
        price: "From $89/user/month (Essentials)",
        bestFor: "Family law firms needing integrations and scalability",
        reasoning: "Clio's custom matter types and document templates can be configured specifically for family law cases -- divorce, custody, adoption, and guardianship. The 250+ integration ecosystem connects with court e-filing systems, accounting tools, and calendar applications. For family law firms planning to grow, Clio provides the best foundation.",
        pros: ["Custom matter types for each family law case type", "250+ integrations including court e-filing", "Client portal with secure document sharing", "Best mobile app for court appearances", "Scalable from solo to mid-size firm"],
        cons: ["Higher starting price than MyCase", "Requires custom setup for family law workflows"],
        affiliateUrl: "https://www.clio.com/signup/",
      },
    ],
    keyFeatures: [
      { icon: "\U0001F4C4", title: "Family Law Document Templates", description: "Pre-built templates for divorce petitions, custody agreements, parenting plans, financial affidavits, and property settlement worksheets." },
      { icon: "\U0001F4AC", title: "Client Communication Portal", description: "Secure messaging and document sharing with emotionally invested clients. Reduce phone calls and create a documented communication trail." },
      { icon: "\U0001F4C5", title: "Court Deadline Tracking", description: "Track filing deadlines, hearing dates, discovery cutoffs, and statute of limitations across all active family law cases." },
      { icon: "\U0001F4B0", title: "Trust Accounting", description: "IOLTA-compliant trust accounting for retainer management. Track client trust balances and generate 3-way reconciliation reports." },
      { icon: "\u270D\uFE0F", title: "eSignature", description: "Get retainer agreements, settlement offers, and consent orders signed electronically. Critical for family law where signatures are frequent." },
      { icon: "\u23F1\uFE0F", title: "Time Tracking", description: "Accurate hourly billing with automatic time capture. Family law cases often involve extensive client communication that must be tracked." },
    ],
    pricingTable: [
      { software: "Smokeball", starter: "From $149/mo", mid: "Custom", enterprise: "Custom", freeTrial: true },
      { software: "MyCase", starter: "$39/user/mo", mid: "$89/user/mo", enterprise: "$109/user/mo", freeTrial: true },
      { software: "Clio", starter: "$49/user/mo", mid: "$89/user/mo", enterprise: "$119/user/mo", freeTrial: true },
    ],
    faqs: [
      { question: "What is the best legal software for family law attorneys?", answer: "Smokeball is the best choice for family law firms due to its extensive document template library (divorce petitions, custody agreements, parenting plans) and automatic time tracking. MyCase is best for high-touch client communication, and Clio is best for overall practice management with custom workflows." },
      { question: "Does legal software include family law document templates?", answer: "Smokeball includes 20,000+ legal document templates with extensive family law coverage. Clio and MyCase offer document template builders where you can create and customize your own family law templates with auto-fill fields." },
      { question: "How does legal software help with family law client communication?", answer: "MyCase includes a client portal on all plans and unlimited two-way texting on the Pro plan. Clients can check case status, view shared documents, and pay invoices without calling the office. This is critical in family law where clients are emotionally invested and want frequent updates." },
      { question: "Can legal software track child support calculations?", answer: "Most legal PM software doesn't include built-in child support calculators, but you can create custom fields and templates for support calculations. Smokeball's document automation can auto-fill financial data into child support worksheets from matter records." },
      { question: "Is there legal software specifically designed for family law?", answer: "No major standalone family law software exists. General practice management platforms like Smokeball, Clio, and MyCase are the best options, configured with family law document templates, custom matter types, and relevant workflows." },
    ],
    metaTitle: "Best Legal Software for Family Law (2026) | CounselStack",
    metaDescription: "Best legal practice management software for family law attorneys in 2026. Compare Smokeball, MyCase, and Clio for document automation, client communication, and case management.",
  },

  "personal-injury": {
    slug: "personal-injury",
    title: "Best Legal Software for Personal Injury",
    heroHeadline: "Best Legal Software for Personal Injury in 2026",
    heroSubtext: "Case management platforms built for high-volume intake, contingency fee tracking, medical records management, and settlement disbursement.",
    audienceDescription: "Personal injury firms have unique software needs that general practice management tools often miss. High-volume lead intake, contingency fee tracking, medical record management, demand letter automation, and settlement disbursement calculations are essential. PI firms also need to keep plaintiffs informed -- the number one complaint about PI attorneys is lack of communication. The right software directly impacts both case outcomes and client satisfaction.",
    topRecommendations: [
      {
        rank: 1,
        name: "Smokeball",
        tagline: "Best automatic time tracking and PI document automation",
        price: "From $149/month (annual contract)",
        bestFor: "PI firms with 2-25 attorneys",
        reasoning: "Smokeball is the best fit for personal injury firms because of its Autotime feature -- it automatically tracks every second spent on a case without manual timers. For PI firms working on contingency where time tracking matters for case valuation and fee petitions, this is transformative. The document automation generates demand letters and medical record requests from case data.",
        pros: ["Autotime captures billable hours without manual entry", "PI-specific document templates (demand letters, medicals)", "Settlement tracking and distribution calculations", "Intake workflow with lead scoring", "Automatic activity tracking per case"],
        cons: ["Annual contract required", "Opaque pricing structure", "Steeper learning curve for new staff"],
        affiliateUrl: "https://www.smokeball.com/free-trial/",
      },
      {
        rank: 2,
        name: "Clio",
        tagline: "Best integration ecosystem for PI workflows",
        price: "From $89/user/month (Essentials)",
        bestFor: "PI firms needing medical records and lien integrations",
        reasoning: "Clio is the strongest choice for PI firms that need to integrate with medical record retrieval services, lien resolution platforms, and legal funding companies. With 250+ integrations, Clio connects your case management to the entire PI ecosystem. Clio Grow handles high-volume lead intake and conversion tracking.",
        pros: ["250+ integrations with medical records and lien platforms", "Clio Grow for lead intake and conversion", "Client portal reduces plaintiff phone calls", "Custom fields for PI case data", "Trust accounting for settlement disbursements"],
        cons: ["No automatic time tracking like Smokeball", "Higher cost when adding Clio Grow"],
        affiliateUrl: "https://www.clio.com/signup/",
      },
      {
        rank: 3,
        name: "MyCase",
        tagline: "Best client communication for plaintiff satisfaction",
        price: "From $89/user/month (Pro)",
        bestFor: "PI firms where client communication is the biggest bottleneck",
        reasoning: "MyCase Pro wins for PI firms where client communication is the biggest pain point. Unlimited two-way texting keeps plaintiffs updated without clogging your phone. The 8am IQ AI assistant helps draft demand letters and correspondence faster. For PI firms that get complaints about 'my lawyer never calls me back,' MyCase directly solves that problem.",
        pros: ["Unlimited two-way texting with plaintiffs", "AI assistant for demand letter drafting", "Client portal with case status updates", "eSignature for retainer agreements", "Text message intake for new leads"],
        cons: ["No automatic time tracking", "Fewer integrations than Clio for PI ecosystem"],
        affiliateUrl: "https://www.mycase.com/free-trial/",
      },
    ],
    keyFeatures: [
      { icon: "\U0001F4E5", title: "High-Volume Lead Intake", description: "Automated lead capture from web forms, phone, and referrals. Instant follow-up prevents losing cases to competitors who respond faster." },
      { icon: "\U0001F3E5", title: "Medical Records Management", description: "Track medical providers, request records, and organize treatment documentation. Integrate with medical record retrieval services." },
      { icon: "\U0001F4DD", title: "Demand Letter Automation", description: "Generate demand letters from case data using templates. AI-assisted drafting helps create persuasive demand packages faster." },
      { icon: "\U0001F4B0", title: "Settlement Tracking", description: "Track settlement negotiations, calculate disbursements, and manage lien resolutions. Ensure accurate fee distributions on every case." },
      { icon: "\U0001F4AC", title: "Client Communication", description: "Two-way texting, client portal, and automated status updates keep plaintiffs informed. Reduce 'where is my case?' calls by 40%." },
      { icon: "\u23F0", title: "Statute of Limitations Tracking", description: "Automated deadline tracking with warnings for approaching statutes of limitation. Never miss a critical filing deadline." },
    ],
    pricingTable: [
      { software: "Smokeball", starter: "From $149/mo", mid: "Custom", enterprise: "Custom", freeTrial: true },
      { software: "Clio", starter: "$89/user/mo", mid: "$119/user/mo", enterprise: "$149/user/mo", freeTrial: true },
      { software: "MyCase", starter: "$39/user/mo", mid: "$89/user/mo", enterprise: "$109/user/mo", freeTrial: true },
    ],
    faqs: [
      { question: "What is the best case management software for personal injury attorneys?", answer: "Smokeball is the top pick for PI firms due to automatic time tracking (Autotime), PI-specific document templates, and settlement tracking. Clio is best for firms needing deep integrations with medical record services and lien resolution platforms." },
      { question: "Do personal injury firms need time tracking software?", answer: "Yes, even on contingency cases. Accurate time records are essential for fee petitions, case valuation, and firm profitability analysis. Smokeball's Autotime tracks time automatically without manual timers -- critical for PI firms where attorneys resist time entry." },
      { question: "How much does legal software cost for a personal injury firm?", answer: "Expect $89-$149/user/month for quality PI case management. Smokeball starts from $149/month, Clio and MyCase at $89/user/month. The ROI is typically positive within 30 days through improved intake conversion and reduced administrative time." },
      { question: "Can legal software help with medical record requests?", answer: "Yes. Smokeball includes medical record request templates that auto-fill from case data. Clio integrates with third-party medical record retrieval services through its 250+ integration ecosystem. Both approaches save hours per case on medical documentation." },
      { question: "What features reduce client complaints in PI cases?", answer: "Client portals (all three platforms), two-way texting (MyCase Pro, PracticePanther Business), and automated case status updates. MyCase's unlimited texting is especially effective -- plaintiffs can text their attorney instead of calling and waiting on hold." },
    ],
    metaTitle: "Best Legal Software for Personal Injury (2026) | CounselStack",
    metaDescription: "Best legal practice management software for personal injury law firms in 2026. Compare Smokeball, Clio, and MyCase for PI case management, demand letters, and settlement tracking.",
  },

  "real-estate-attorneys": {
    slug: "real-estate-attorneys",
    title: "Best Legal Software for Real Estate Attorneys",
    heroHeadline: "Best Legal Software for Real Estate Attorneys in 2026",
    heroSubtext: "Practice management platforms optimized for closings, title searches, escrow management, and high-volume transactional work.",
    audienceDescription: "Real estate attorneys handle high-volume transactional work with tight closing deadlines, complex document requirements, and trust/escrow accounting obligations. Unlike litigation practices, real estate law is deadline-driven rather than court-driven -- a missed closing date can cost a client their deal. The right software must handle document automation for deeds, title commitments, closing statements, and escrow disbursements with precision.",
    topRecommendations: [
      {
        rank: 1,
        name: "Smokeball",
        tagline: "Best document automation for real estate closings",
        price: "From $149/month (annual contract)",
        bestFor: "Real estate firms processing high-volume closings",
        reasoning: "Smokeball is purpose-built for document-heavy transactional practices like real estate. Its template library includes deeds, title commitments, closing disclosures, HUD-1 statements, and escrow letters. Documents auto-fill from matter data, and the deep Microsoft 365 integration means attorneys can draft in Word with real-time syncing to the case file. Autotime captures every minute spent on closings automatically.",
        pros: ["Real estate-specific document templates", "Autotime for automatic time tracking", "Deep Microsoft 365 integration", "Practice area workflows for closings", "Automatic version control on all documents"],
        cons: ["Annual contract required", "Higher starting price than competitors", "Opaque per-user pricing"],
        affiliateUrl: "https://www.smokeball.com/free-trial/",
      },
      {
        rank: 2,
        name: "CosmoLex",
        tagline: "Best built-in trust/escrow accounting for real estate",
        price: "From $109/user/month",
        bestFor: "Real estate attorneys needing trust and escrow accounting",
        reasoning: "Real estate attorneys manage significant escrow funds with strict bar compliance requirements. CosmoLex is the only platform with full double-entry accounting built in, including trust accounting with 3-way reconciliation. No QuickBooks sync issues, no data discrepancies between systems -- critical when handling six-figure escrow accounts.",
        pros: ["Built-in trust accounting with 3-way reconciliation", "Full double-entry accounting (no QuickBooks needed)", "Escrow fund tracking and reporting", "Single platform for PM + accounting", "Compliance reporting for bar audits"],
        cons: ["Higher per-user price", "Smaller integration library (~20)", "Less polished interface"],
        affiliateUrl: "https://www.cosmolex.com/free-trial/",
      },
      {
        rank: 3,
        name: "Clio",
        tagline: "Best ecosystem for real estate firms with diverse needs",
        price: "From $89/user/month (Essentials)",
        bestFor: "Real estate firms handling both transactional and litigation work",
        reasoning: "Clio provides the most flexible platform for real estate firms that also handle title disputes, boundary litigation, or landlord-tenant cases alongside closings. Custom matter types, document templates, and 250+ integrations (including title company systems) make it adaptable to any real estate workflow.",
        pros: ["Custom matter types for different transaction types", "250+ integrations including title company systems", "Client portal for secure document exchange", "Trust accounting on all plans", "Best mobile app for on-site closings"],
        cons: ["No built-in firm accounting", "Requires custom template setup for real estate"],
        affiliateUrl: "https://www.clio.com/signup/",
      },
    ],
    keyFeatures: [
      { icon: "\U0001F3E0", title: "Closing Management", description: "Track all closing deadlines, documents, and parties in one place. Automated checklists ensure nothing is missed before closing day." },
      { icon: "\U0001F4C4", title: "Real Estate Document Templates", description: "Pre-built templates for deeds, title commitments, closing disclosures, escrow letters, and HUD-1 statements with auto-fill from matter data." },
      { icon: "\U0001F4B0", title: "Trust & Escrow Accounting", description: "IOLTA-compliant trust accounting with escrow fund tracking, 3-way reconciliation, and disbursement management for every closing." },
      { icon: "\u23F0", title: "Deadline Tracking", description: "Automated closing date tracking, contingency deadlines, and title search timelines. Never miss a closing or inspection period." },
      { icon: "\u270D\uFE0F", title: "eSignature", description: "Get closing documents, title affidavits, and settlement statements signed electronically. Essential for remote or out-of-state closings." },
      { icon: "\U0001F4C2", title: "Document Management", description: "Organize title searches, surveys, inspection reports, and closing packages per transaction. Full-text search across all documents." },
    ],
    pricingTable: [
      { software: "Smokeball", starter: "From $149/mo", mid: "Custom", enterprise: "Custom", freeTrial: true },
      { software: "CosmoLex", starter: "$109/user/mo", mid: "$129/user/mo", enterprise: "Custom", freeTrial: true },
      { software: "Clio", starter: "$49/user/mo", mid: "$89/user/mo", enterprise: "$119/user/mo", freeTrial: true },
    ],
    faqs: [
      { question: "What is the best legal software for real estate attorneys?", answer: "Smokeball is the top pick for real estate attorneys due to its document automation (deeds, closings, title documents), automatic time tracking, and practice area workflows. CosmoLex is best for attorneys needing built-in trust/escrow accounting." },
      { question: "Do real estate attorneys need built-in accounting?", answer: "Trust/escrow accounting is essential and included in all major platforms. For full firm accounting (P&L, balance sheets), CosmoLex eliminates QuickBooks by building it in. Other platforms require QuickBooks or Xero integration." },
      { question: "Can legal software handle closing checklists?", answer: "Yes. Smokeball has pre-built closing workflows with automated checklists. Clio's matter templates can be configured with closing tasks and deadlines. Both ensure every document, signature, and disbursement is tracked before closing day." },
      { question: "How does legal software help with title searches?", answer: "Legal PM software organizes title search documents within the matter file, tracks title search deadlines, and stores title commitments with version history. Clio integrates with title company systems through its 250+ integration ecosystem." },
      { question: "Is there software specifically for real estate law firms?", answer: "No major standalone real estate law software exists for general practice management. Smokeball, CosmoLex, and Clio are the best general platforms with real estate-specific document templates and escrow accounting capabilities." },
    ],
    metaTitle: "Best Legal Software for Real Estate Attorneys (2026) | CounselStack",
    metaDescription: "Best legal practice management software for real estate attorneys in 2026. Compare Smokeball, CosmoLex, and Clio for closing management, document automation, and escrow accounting.",
  },

  "immigration-attorneys": {
    slug: "immigration-attorneys",
    title: "Best Legal Software for Immigration Attorneys",
    heroHeadline: "Best Legal Software for Immigration Attorneys in 2026",
    heroSubtext: "Case management platforms with USCIS form auto-fill, processing time tracking, and multi-language client intake.",
    audienceDescription: "Immigration law has specialized software requirements that general practice management tools cannot fully address. Attorneys need USCIS form auto-fill across 100+ form types, case status tracking against government processing times, multi-language client questionnaires, and workflows for petitions, RFEs, and appeals. The volume of forms per case and the consequences of errors make immigration-specific features essential, not optional.",
    topRecommendations: [
      {
        rank: 1,
        name: "Docketwise",
        tagline: "Purpose-built immigration software with USCIS form auto-fill",
        price: "From $69/user/month",
        bestFor: "Immigration firms of all sizes",
        reasoning: "Docketwise is purpose-built for immigration law. It auto-fills USCIS forms from your case data, tracks case statuses against USCIS processing times, manages questionnaires in multiple languages, and handles the unique workflow of immigration cases. No general-purpose platform comes close to this level of immigration-specific functionality.",
        pros: ["Auto-fills 100+ USCIS forms from case data", "Case status tracking with USCIS processing times", "Multi-language client questionnaires", "Bulk form generation for family petitions", "Immigration-specific case workflows"],
        cons: ["Not a full practice management platform", "Limited general billing features", "Smaller company than Clio or MyCase"],
        affiliateUrl: "https://www.docketwise.com/",
      },
      {
        rank: 2,
        name: "Clio",
        tagline: "Best general platform with immigration flexibility",
        price: "From $89/user/month (Essentials)",
        bestFor: "Multi-practice firms with immigration work",
        reasoning: "For immigration attorneys who also handle other practice areas (family law, business law), Clio provides the strongest general practice management platform with enough flexibility to handle immigration workflows. Custom matter types, 250+ integrations (including Docketwise), and trust accounting make it a solid foundation for any practice mix.",
        pros: ["250+ integrations including Docketwise", "Custom matter types for immigration cases", "Trust accounting for IOLTA compliance", "Full mobile app for case access anywhere", "Scales from solo to large firm"],
        cons: ["No native USCIS form auto-fill", "Requires custom setup for immigration workflows", "Higher cost than Docketwise alone"],
        affiliateUrl: "https://www.clio.com/signup/",
      },
      {
        rank: 3,
        name: "INSZoom",
        tagline: "Enterprise solution for corporate immigration",
        price: "Custom pricing (contact for quote)",
        bestFor: "Corporate immigration and large firms processing 100+ cases monthly",
        reasoning: "INSZoom is the enterprise solution for corporate immigration departments and large immigration firms processing high volumes of H-1B, L-1, and PERM cases. Its compliance tracking, government processing time dashboards, and employer petition management are unmatched for corporate immigration work.",
        pros: ["Corporate immigration case management", "H-1B cap tracking and compliance", "PERM labor certification workflow", "Government processing time dashboards", "Employer portal for corporate clients"],
        cons: ["Enterprise pricing not suitable for small firms", "Complex implementation required", "Not designed for individual immigration cases"],
        affiliateUrl: "https://www.inszoom.com/",
      },
    ],
    keyFeatures: [
      { icon: "\U0001F4CB", title: "USCIS Form Auto-Fill", description: "Auto-fill 100+ USCIS forms (I-130, I-485, I-765, I-140, etc.) from case data. Eliminate hours of manual form completion per case." },
      { icon: "\U0001F4CA", title: "Processing Time Tracking", description: "Track case status against current USCIS processing times. Know exactly where each case stands and when to expect a response." },
      { icon: "\U0001F30D", title: "Multi-Language Support", description: "Client questionnaires and portal in multiple languages. Essential for serving immigrant clients who may not be fluent in English." },
      { icon: "\U0001F4C1", title: "Immigration Case Types", description: "Pre-built workflows for family petitions, employment visas, asylum, naturalization, and removal defense cases." },
      { icon: "\U0001F4E8", title: "RFE Management", description: "Track Requests for Evidence with deadlines, response templates, and status tracking. Never miss an RFE response deadline." },
      { icon: "\U0001F465", title: "Family Petition Handling", description: "Bulk form generation for family-based petitions. Manage multiple beneficiaries under a single case with linked records." },
    ],
    pricingTable: [
      { software: "Docketwise", starter: "$69/user/mo", mid: "Custom", enterprise: "Custom", freeTrial: true },
      { software: "Clio", starter: "$49/user/mo", mid: "$89/user/mo", enterprise: "$119/user/mo", freeTrial: true },
      { software: "INSZoom", starter: "Custom", mid: "Custom", enterprise: "Custom", freeTrial: false },
    ],
    faqs: [
      { question: "What is the best software for immigration lawyers?", answer: "Docketwise is the best immigration-specific software -- it auto-fills USCIS forms and tracks case statuses against processing times. For firms that also handle other practice areas, Clio provides the best general platform with immigration workflow support." },
      { question: "Can legal software auto-fill USCIS immigration forms?", answer: "Yes. Docketwise auto-fills over 100 USCIS forms (I-130, I-485, I-765, I-140, etc.) from your case data. This eliminates hours of manual form completion per case and reduces errors that lead to RFEs." },
      { question: "How much does immigration law software cost?", answer: "Docketwise starts at $69/user/month, making it the most affordable immigration-specific option. Clio starts at $49/user/month for general practice management. INSZoom requires custom pricing for enterprise deployments." },
      { question: "Do I need immigration-specific software or general legal software?", answer: "If 50%+ of your caseload is immigration, Docketwise will save you significant time with form auto-fill and USCIS tracking. If immigration is a secondary practice area, Clio's general platform with custom workflows is more cost-effective." },
      { question: "Can Docketwise and Clio work together?", answer: "Yes. Clio's 250+ integrations include Docketwise. Many immigration firms use Docketwise for immigration-specific workflows (form filling, USCIS tracking) alongside Clio for general practice management (billing, client portal, time tracking)." },
    ],
    metaTitle: "Best Legal Software for Immigration Attorneys (2026) | CounselStack",
    metaDescription: "Best legal software for immigration lawyers in 2026. Compare Docketwise, Clio, and INSZoom for USCIS form auto-fill, case tracking, and immigration case management.",
  },

  "criminal-defense": {
    slug: "criminal-defense",
    title: "Best Legal Software for Criminal Defense",
    heroHeadline: "Best Legal Software for Criminal Defense in 2026",
    heroSubtext: "Practice management tools for public defenders, private criminal defense attorneys, and defense firms handling high-volume caseloads.",
    audienceDescription: "Criminal defense attorneys face unique challenges: high caseload volumes, frequent court appearances, tight discovery deadlines, and clients who may be incarcerated or difficult to reach. Software needs to handle case tracking across multiple courts, manage evidence and discovery documents, track court dates and continuances, and facilitate communication with clients who may have limited technology access. Many criminal defense attorneys also handle flat-fee arrangements rather than hourly billing.",
    topRecommendations: [
      {
        rank: 1,
        name: "MyCase",
        tagline: "Best value with client communication tools for defense work",
        price: "From $39/user/month",
        bestFor: "Criminal defense attorneys and small defense firms",
        reasoning: "MyCase is the best choice for criminal defense attorneys because of its combination of affordability and client communication features. The client portal lets defendants and family members check case status 24/7, reducing phone calls from anxious families. Two-way texting on Pro keeps clients informed between court dates. At $39/user/month for Basic, it's accessible for solo defense attorneys and public defenders.",
        pros: ["Lowest entry price at $39/user/month", "Client portal accessible to families", "Two-way texting for client updates", "AI assistant helps draft motions and briefs", "10-day free trial, no credit card"],
        cons: ["No criminal defense-specific templates built in", "Fewer integrations than Clio"],
        affiliateUrl: "https://www.mycase.com/free-trial/",
      },
      {
        rank: 2,
        name: "PracticePanther",
        tagline: "Self-contained platform with flat-fee billing support",
        price: "From $49/user/month",
        bestFor: "Defense attorneys using flat-fee billing structures",
        reasoning: "PracticePanther excels for criminal defense attorneys who use flat-fee billing structures. The platform handles both hourly and flat-fee arrangements natively, and the built-in eSignature gets retainer agreements signed immediately -- critical when a client needs representation urgently. Free data migration and intake forms help onboard new clients quickly.",
        pros: ["Native flat-fee and hourly billing support", "Built-in eSignature for immediate retainer signing", "Intake forms for fast client onboarding", "Built-in two-way texting", "Free data migration from other platforms"],
        cons: ["No criminal defense-specific workflows", "Mid-tier pricing at entry level"],
        affiliateUrl: "https://www.practicepanther.com/free-trial/",
      },
      {
        rank: 3,
        name: "Clio",
        tagline: "Best platform for high-volume defense practices",
        price: "From $89/user/month (Essentials)",
        bestFor: "Defense firms handling 100+ active cases",
        reasoning: "Clio is the best choice for defense firms managing high-volume caseloads across multiple courts. Custom matter types for felonies, misdemeanors, DUI, and drug cases keep each case type organized. The 250+ integrations include court calendar systems and e-filing platforms. For firms with multiple attorneys sharing cases, Clio's collaboration features are unmatched.",
        pros: ["Custom matter types for each criminal case type", "250+ integrations with court systems", "Multi-attorney case collaboration", "Best mobile app for court appearances", "Scalable for growing defense firms"],
        cons: ["Higher starting price for entry-level plan", "Requires custom configuration for defense work"],
        affiliateUrl: "https://www.clio.com/signup/",
      },
    ],
    keyFeatures: [
      { icon: "\u2696\uFE0F", title: "Court Calendar Management", description: "Track hearings, arraignments, trials, and continuances across multiple courts. Sync with court e-calendaring systems." },
      { icon: "\U0001F4C1", title: "Discovery Management", description: "Organize and track discovery documents, evidence files, and police reports. Full-text search across all case documents." },
      { icon: "\U0001F4AC", title: "Client Communication", description: "Client portal and texting for defendants and family members. Critical when clients are incarcerated or have limited phone access." },
      { icon: "\U0001F4B5", title: "Flat-Fee Billing", description: "Support for flat-fee arrangements alongside hourly billing. Track flat fees by case type and generate payment plans." },
      { icon: "\U0001F4DD", title: "Motion Templates", description: "Document templates for motions to suppress, dismiss, continue, and other common criminal defense filings." },
      { icon: "\u23F0", title: "Deadline Tracking", description: "Track speedy trial deadlines, discovery response dates, and filing deadlines. Automated warnings for approaching deadlines." },
    ],
    pricingTable: [
      { software: "MyCase", starter: "$39/user/mo", mid: "$89/user/mo", enterprise: "$109/user/mo", freeTrial: true },
      { software: "PracticePanther", starter: "$49/user/mo", mid: "$69/user/mo", enterprise: "$89/user/mo", freeTrial: true },
      { software: "Clio", starter: "$49/user/mo", mid: "$89/user/mo", enterprise: "$119/user/mo", freeTrial: true },
    ],
    faqs: [
      { question: "What is the best legal software for criminal defense attorneys?", answer: "MyCase is the best value for criminal defense attorneys at $39/user/month with client portal and texting features. PracticePanther is best for flat-fee billing. Clio is best for high-volume defense firms needing court calendar integrations and multi-attorney collaboration." },
      { question: "Can legal software handle flat-fee criminal defense billing?", answer: "Yes. PracticePanther and MyCase both support flat-fee billing alongside hourly billing. You can set up flat fees by case type (DUI, misdemeanor, felony) and generate payment plans for clients." },
      { question: "How does legal software help with discovery management?", answer: "All three platforms provide document management with full-text search, version control, and matter-linked storage. Upload police reports, evidence photos, witness statements, and expert reports -- all searchable and organized by case." },
      { question: "Is there legal software specifically for public defenders?", answer: "No major standalone public defender software exists for case management. MyCase Basic at $39/user/month is the most affordable option for public defenders. Some public defender offices use Clio with custom configurations for high-volume caseload management." },
      { question: "Can family members access case information through the software?", answer: "Yes. MyCase and Clio both offer client portals where you can grant access to family members. This is critical in criminal defense where defendants may be incarcerated and family members need case status updates." },
    ],
    metaTitle: "Best Legal Software for Criminal Defense (2026) | CounselStack",
    metaDescription: "Best legal practice management software for criminal defense attorneys in 2026. Compare MyCase, PracticePanther, and Clio for case management, client communication, and billing.",
  },
};

export function getAudience(slug: string): AudiencePage | undefined {
  return audiences[slug];
}

export function getAllAudienceSlugs(): string[] {
  return Object.keys(audiences);
}
